feature/SP-4906, bootstrap script (#1)
* draft build script

* test action

* create main func

* fixed cp config

* add build qemu/ovmf

* test free space

* test free space 2

* fixed nested source

* gitignore

* test free space

* test self-hosted

* test

* pack package

* test release

* fix github token

* tag

* fix asset path

* fixed path

* token for upload asset

* non empty file

* fix archive

* real build

* non interactrive

* install script

* added release input

* some minor changes in install script

* rm standart action

* added new line

* readme, change pccs url to sp

* fix readme

* update tdx module

diff --git a/.github/workflows/build-packages-self-hosted.yml b/.github/workflows/build-packages-self-hosted.yml
--- a/.github/workflows/build-packages-self-hosted.yml
+++ b/.github/workflows/build-packages-self-hosted.yml
@@ -1,30 +1,49 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Build packages self-hosted
 
-# Controls when the workflow will run
 on:
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    inputs:
+      release_version:
+        description: "Release name (format v1.2.3)"
+        required: true
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
-    runs-on:  ubuntu-24.04
+    runs-on: sp-zen-tech-linux-x64
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Validate release version format
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          version_regex="^v[0-9]+\.[0-9]+\.[0-9]+$"
+          if [[ ! "${{ github.event.inputs.release_version }}" =~ $version_regex ]]; then
+            echo "Error: Invalid release version format. Expected format: v1.2.3"
+            exit 1
+          fi
+
+      - name: Run docker build
+        run: |
+          NON_INTERACTIVE=1 FORCE_REBUILD_CONTAINER=1 ./build_in_docker.sh
+
+      - name: Create GitHub Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+        with:
+          tag_name: "${{ github.event.inputs.release_version }}"
+          release_name: "Release ${{ github.event.inputs.release_version }}"
+          draft: false
+          prerelease: false
+
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./build/package.tar.gz
+          asset_name: package.tar.gz
+          asset_content_type: application/gzip
