added release input

diff --git a/.github/workflows/build-packages-self-hosted.yml b/.github/workflows/build-packages-self-hosted.yml
--- a/.github/workflows/build-packages-self-hosted.yml
+++ b/.github/workflows/build-packages-self-hosted.yml
@@ -2,6 +2,10 @@ name: Build packages self-hosted
 
 on:
   workflow_dispatch:
+    inputs:
+      release_version:
+        description: "Release name (format v1.2.3)"
+        required: true
 
 jobs:
   build:
@@ -9,6 +13,14 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Validate release version format
+        run: |
+          version_regex="^v[0-9]+\.[0-9]+\.[0-9]+$"
+          if [[ ! "${{ github.event.inputs.release_version }}" =~ $version_regex ]]; then
+            echo "Error: Invalid release version format. Expected format: v1.2.3"
+            exit 1
+          fi
 
       - name: Run docker build
         run: |
@@ -21,8 +33,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
         with:
-          tag_name: "1.0.1"
-          release_name: Release 1.0.1
+          tag_name: "${{ github.event.inputs.release_version }}"
+          release_name: "Release ${{ github.event.inputs.release_version }}"
           draft: false
           prerelease: false
 
